
export const MODE_SELECTED = "MODE_SELECTED"
export const GUEST_TYPE_SELECTED = "GUEST_TYPE_SELECTED"
export const GET_CUSTOMERS = "GET_CUSTOMERS"
export const GET_CHECKINS = "GET_CHECKINS"
export const GET_MESSAGES = "GET_MESSAGES"
export const AUTHENTICATE_USER = "AUTHENTICATE_USER"
export const GUEST_CHECKIN = "GUEST_CHECKIN"
export const GUEST_CHECKOUT = "GUEST_CHECKOUT"